student_email: kobik2@yandex.ru
postgres_cluster:
  hosts:
  - address: postgres-db
    port: 5432
  user: postgres
  password: postgres
  db_name: postgres
  ssl_mode: disable
  use_closest_node: false